version: "3"

services: 
    api:
        build: .
        command: bash -c "uvicorn main:app --reload --host 0.0.0.0"
        environment: 
            - SECRET_KEY=${ALGORITHM}
            - ALGORITHM=${ALGORITHM}
        volumes: 
            - ./:/src
        ports: 
            - "8000:8000"
      
